<script lang="ts">
	import katex from 'katex';

	let { math, displayMode = false }: { math: string; displayMode?: boolean } = $props();

	const html = $derived(
		katex.renderToString(math, {
			displayMode,
			throwOnError: false
		})
	);
</script>

<!-- KaTeX output is trusted (generated by katex.renderToString), so {@html} is safe here. -->
{@html html}
